version: 2.1

#orbs:
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
         pkg-manager: npm
      - run:
         echo "installing dependecies..."
         npm install
  test:
    docker:
      -  image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
         pkg-manager: npm
      - run:
         echo "installing dependecies..."
         npm run test
#TODO:  add publish job

# workflow
workflows:
  # Name of the workflow is simple_workflow
  simple_workflow:
    jobs:
      - build
      - test:
         requires:
         - build
